# Copyright (C) 2022 - : Kristofer Tingdahl
# Licensed under the Mozilla public license 2.0

name: tingdahl-observatory-http-cli-scanner
title: Observatory http cli scanner
license: MPL-2.0
website: https://github.com/tingdahl/http-observatory-local-scan
base: core24 
summary: Score your site's HTTPS practices from a CLI scanner
version: git
description: |
  Mozilla Observatory scans websites for security issues. This is the cli
  version of observability that allows CI/CD tooling to test websites
  as a part of the build and release process.
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  ppc64el:
  s390x:
  armhf:

parts:
  httpobs-local-scan :
    plugin: python
    source: .
    build-packages:
      - git

apps:
  httpobs-local-scan :
    command: bin/httpobs-local-scan 
    plugs:
      - network
